"""initial tables

Revision ID: 0cb61fd871b2
Revises: 
Create Date: 2026-02-15 20:08:39.649144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb61fd871b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openId', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('passwordHash', sa.String(length=255), nullable=True),
    sa.Column('loginMethod', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastSignedIn', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('openId')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scriptContent', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'parsing', 'parsed', 'generating_storyboard', 'generating_videos', 'assembling', 'completed', 'failed', name='project_status'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('errorMessage', sa.Text(), nullable=True),
    sa.Column('trailerUrl', sa.String(length=500), nullable=True),
    sa.Column('trailerKey', sa.String(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visualDescription', sa.Text(), nullable=True),
    sa.Column('imageUrl', sa.String(length=512), nullable=True),
    sa.Column('imageKey', sa.String(length=512), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finalMovies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('movieUrl', sa.String(length=512), nullable=True),
    sa.Column('movieKey', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assembling', 'completed', 'failed', name='movie_status'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('sceneNumber', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('setting', sa.String(length=255), nullable=True),
    sa.Column('characters', sa.Text(), nullable=True),
    sa.Column('dialogue', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visualDescription', sa.Text(), nullable=True),
    sa.Column('imageUrl', sa.String(length=512), nullable=True),
    sa.Column('imageKey', sa.String(length=512), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generatedVideos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sceneId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('videoUrl', sa.String(length=512), nullable=True),
    sa.Column('videoKey', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'generating', 'completed', 'failed', name='video_status'), nullable=False),
    sa.Column('errorMessage', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sceneId'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storyboardImages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sceneId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=512), nullable=False),
    sa.Column('imageKey', sa.String(length=512), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'generating', 'completed', 'failed', name='storyboard_status'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sceneId'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videoPrompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sceneId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('style', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sceneId'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videoPrompts')
    op.drop_table('storyboardImages')
    op.drop_table('generatedVideos')
    op.drop_table('settings')
    op.drop_table('scenes')
    op.drop_table('finalMovies')
    op.drop_table('characters')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
